// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: guid.proto

package guid

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	High32Allocator_Allocate_FullMethodName = "/guid.High32Allocator/Allocate"
)

// High32AllocatorClient is the client API for High32Allocator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type High32AllocatorClient interface {
	Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error)
}

type high32AllocatorClient struct {
	cc grpc.ClientConnInterface
}

func NewHigh32AllocatorClient(cc grpc.ClientConnInterface) High32AllocatorClient {
	return &high32AllocatorClient{cc}
}

func (c *high32AllocatorClient) Allocate(ctx context.Context, in *AllocateRequest, opts ...grpc.CallOption) (*AllocateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllocateResponse)
	err := c.cc.Invoke(ctx, High32Allocator_Allocate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// High32AllocatorServer is the server API for High32Allocator service.
// All implementations must embed UnimplementedHigh32AllocatorServer
// for forward compatibility.
type High32AllocatorServer interface {
	Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error)
	mustEmbedUnimplementedHigh32AllocatorServer()
}

// UnimplementedHigh32AllocatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHigh32AllocatorServer struct{}

func (UnimplementedHigh32AllocatorServer) Allocate(context.Context, *AllocateRequest) (*AllocateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Allocate not implemented")
}
func (UnimplementedHigh32AllocatorServer) mustEmbedUnimplementedHigh32AllocatorServer() {}
func (UnimplementedHigh32AllocatorServer) testEmbeddedByValue()                         {}

// UnsafeHigh32AllocatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to High32AllocatorServer will
// result in compilation errors.
type UnsafeHigh32AllocatorServer interface {
	mustEmbedUnimplementedHigh32AllocatorServer()
}

func RegisterHigh32AllocatorServer(s grpc.ServiceRegistrar, srv High32AllocatorServer) {
	// If the following call pancis, it indicates UnimplementedHigh32AllocatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&High32Allocator_ServiceDesc, srv)
}

func _High32Allocator_Allocate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(High32AllocatorServer).Allocate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: High32Allocator_Allocate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(High32AllocatorServer).Allocate(ctx, req.(*AllocateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// High32Allocator_ServiceDesc is the grpc.ServiceDesc for High32Allocator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var High32Allocator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "guid.High32Allocator",
	HandlerType: (*High32AllocatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Allocate",
			Handler:    _High32Allocator_Allocate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "guid.proto",
}
