// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: guid.proto

package guid

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllocateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_guid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_guid_proto_rawDescGZIP(), []int{0}
}

func (x *AllocateRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AllocateRequest) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Env           string                 `protobuf:"bytes,2,opt,name=env,proto3" json:"env,omitempty"`
	Value         uint32                 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_guid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_guid_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateResponse) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *AllocateResponse) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *AllocateResponse) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_guid_proto protoreflect.FileDescriptor

const file_guid_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"guid.proto\x12\x04guid\"=\n" +
	"\x0fAllocateRequest\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\"T\n" +
	"\x10AllocateResponse\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x10\n" +
	"\x03env\x18\x02 \x01(\tR\x03env\x12\x14\n" +
	"\x05value\x18\x03 \x01(\rR\x05value2L\n" +
	"\x0fHigh32Allocator\x129\n" +
	"\bAllocate\x12\x15.guid.AllocateRequest\x1a\x16.guid.AllocateResponseB\tZ\a../guidb\x06proto3"

var (
	file_guid_proto_rawDescOnce sync.Once
	file_guid_proto_rawDescData []byte
)

func file_guid_proto_rawDescGZIP() []byte {
	file_guid_proto_rawDescOnce.Do(func() {
		file_guid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guid_proto_rawDesc), len(file_guid_proto_rawDesc)))
	})
	return file_guid_proto_rawDescData
}

var file_guid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_guid_proto_goTypes = []any{
	(*AllocateRequest)(nil),  // 0: guid.AllocateRequest
	(*AllocateResponse)(nil), // 1: guid.AllocateResponse
}
var file_guid_proto_depIdxs = []int32{
	0, // 0: guid.High32Allocator.Allocate:input_type -> guid.AllocateRequest
	1, // 1: guid.High32Allocator.Allocate:output_type -> guid.AllocateResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guid_proto_init() }
func file_guid_proto_init() {
	if File_guid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guid_proto_rawDesc), len(file_guid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guid_proto_goTypes,
		DependencyIndexes: file_guid_proto_depIdxs,
		MessageInfos:      file_guid_proto_msgTypes,
	}.Build()
	File_guid_proto = out.File
	file_guid_proto_goTypes = nil
	file_guid_proto_depIdxs = nil
}
